#Permission level required
sudo: required
#services required
services:
  - docker
#commands/steps to be executed before to run our tests which are build image with tag (for convinience)
before_install:
 - docker build -t ballamouli91/docker-react-frontend:latest -f Dockerfile.dev .
#script section suppose to conatain all commands to run our test suite, if test suite exit code is zero then travis feel tests are passed
# as we know that npm run tests just sites and hangs for waiting from us, so we need pass extra comand -- -- coverage to run tests and exits out of terminal

script:
#tests run with coverage
- docker run ballamouli91/docker-react-frontend npm run test -- --coverage

#deploystage
deploy:
 provider: elasticbeanstalk
 region: "us-west-2"
 app: "docker"
 env: "Docker-env"
#s3 bucket name where travis will put code and image in AWS, Which automatically created when we create elasticbeanstalk
 bucket_name: "elasticbeanstalk-us-west-2-306476627547"
 #bucket path is app name
 bucket_path: "docker"
 on:
  branch: master
#update API keys for travis to communicate with AWS EBS, access it from travis secrets
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

 